Add MariaDB OpsReq and Autoscaler Docs
kubedb/docs pull request #171
Opened 2022-01-19 07:35 UTC by spectro30

2022-02-04 09:41 UTC, DRoyyy requested changes

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/scaling/vertical-scaling/cluster/index.md
> +$ kubectl get pod -n demo sample-mariadb -o json | jq '.spec.containers[].resources'
$ kubectl get pod -n demo sample-mariadb-0 -o json | jq '.spec.containers[].resources'

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/upgrading/cluster/index.md
> +- `spec.upgrade.targetVersion` specifies the expected version of the database `4.0.5`.
`spec.upgrade.targetVersion` specifies the expected version of the database `10.5.8`.
//as per the yaml

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/volume-expansion/volume-expansion/index.md
> +We can see from the output the `topolvm-provisioner` storage class has `ALLOWVOLUMEEXPANSION` field as true. So, this storage class supports volume expansion. We can use it.
So, this storage class supports volume expansion. We can use it. You can install topolvm from [here](https://github.com/topolvm/topolvm)

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/volume-expansion/volume-expansion/index.md
> +$ kubectl get mariadbopsrequest -n demo
$ watch kubectl get mariadbopsrequest -n demo
//as per the above description

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/upgrading/cluster/index.md
> +kubectl delete mg -n demo sample-mariadb
$ kubectl delete mariadb -n demo sample-mariadb

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/upgrading/cluster/index.md
> +kubectl delete mariadbopsrequest -n demo mdops-upgrade
$ kubectl delete mariadbopsrequest -n demo mdops-upgrade

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/scaling/vertical-scaling/cluster/index.md
> +kubectl delete mariadb -n demo sample-mariadb
$ kubectl delete mariadb -n demo sample-mariadb

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/scaling/vertical-scaling/cluster/index.md
> +kubectl delete mariadbopsrequest -n demo mdops-vscale
$ kubectl delete mariadbopsrequest -n demo mdops-vscale

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/scaling/horizontal-scaling/cluster/index.md
> +kubectl delete mariadb -n demo sample-mariadb
$ kubectl delete mariadb -n demo sample-mariadb

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/scaling/horizontal-scaling/cluster/index.md
> +kubectl delete mariadbopsrequest -n demo  mdops-scale-horizontal-up mdops-scale-horizontal-down
$ kubectl delete mariadbopsrequest -n demo  mdops-scale-horizontal-up mdops-scale-horizontal-down

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/volume-expansion/volume-expansion/index.md
> +kubectl delete mg -n demo sample-mariadb
$ kubectl delete mariadb -n demo sample-mariadb

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/volume-expansion/volume-expansion/index.md
> +kubectl delete mariadbopsrequest -n demo md-online-volume-expansion
$ kubectl delete mariadbopsrequest -n demo md-online-volume-expansion

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure/cluster/index.md
> +kubectl delete mariadb -n demo sample-mariadb
$ kubectl delete mariadb -n demo sample-mariadb

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure/cluster/index.md
> +kubectl delete mariadbopsrequest -n demo mdops-reconfigure-config mdops-reconfigure-remove
$ kubectl delete mariadbopsrequest -n demo mdops-reconfigure-config mdops-reconfigure-remove

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +kubectl delete mariadb -n demo --all
$ kubectl delete mariadb -n demo --all

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +kubectl delete issuer -n demo --all
$ kubectl delete issuer -n demo --all

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +kubectl delete mariadbopsrequest -n demo --all
$ kubectl delete mariadbopsrequest -n demo --all

2022-02-04 09:41 UTC, DRoyyy commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +kubectl delete ns demo
$ kubectl delete ns demo

2022-02-15 04:58 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/examples/sample-mariadb.yaml
> +    storageClassName: "topolvm-provisioner"
we use kind for local cluster setup where default storage class is standard which doesn't support pvc related metrics. So we are using 'topolvm-provisioner' storage-class

2022-02-15 04:58 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +    "topolvm.cybozu.com/capacity": "1"
we use kind for local cluster setup where default storage class is standard which doesn't support pvc related metrics. So we are using 'topolvm-provisioner' storage-class

2022-02-15 04:59 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +    "topolvm.cybozu.com/capacity": "1"
last comment

2022-02-15 04:59 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +    storageClassName: "topolvm-provisioner"
last comment

2022-02-15 05:03 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +    Status:                True
fixed

2022-02-15 05:03 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +  Recommendation:
fixed

2022-02-15 05:05 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +- `spec.storage.mariadb.usageThreshold` specifies storage usage threshold, if storage usage exceeds `60%` then storage autoscaling will be triggered.
fixed

2022-02-15 05:05 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +- `spec.storage.mariadb.scalingThreshold` specifies the scaling threshold. Storage will be scaled to `50%` of the current amount.
fixed

2022-02-15 05:08 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +$ kubectl describe mariadbautoscaler mdas-storage -n demo
fixed

2022-02-15 05:09 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +      Usage Threshold:    60
fixed

2022-02-15 05:09 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +      Scaling Threshold:  50
fixed

2022-02-15 05:10 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +So, from the above output we can see that the storage usage is 83%, which exceeded the `usageThreshold` 60%.
fixed

2022-02-15 05:13 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/storage/cluster/index.md
> +Name:         mdas-storage
fixed

2022-02-15 05:14 UTC, spectro30 commented on docs/guides/mariadb/concepts/opsrequest/index.md
> +If you want to upgrade you MariaDB version, you have to specify the `spec.upgrade` section that specifies the desired version information. This field consists of the following sub-field:
fixed

2022-02-15 05:18 UTC, spectro30 commented on docs/guides/mariadb/reconfigure/standalone/index.md
> +- `spec.databaseRef.name` specifies that we are reconfiguring `mops-reconfigure-standalone` database.
fixed

2022-02-15 05:20 UTC, spectro30 commented on docs/guides/mariadb/reconfigure/cluster/index.md
> +- `spec.databaseRef.name` specifies that we are reconfiguring `mops-reconfigure-cluster` database.
fixed

2022-02-15 05:21 UTC, spectro30 commented on docs/guides/mariadb/reconfigure/standalone/index.md
> +- `spec.databaseRef.name` specifies that we are reconfiguring `mops-reconfigure-standalone` database.
fixed

2022-02-15 05:22 UTC, spectro30 commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +$ kubectl get secrets -n demo mg-rs-auth -o jsonpath='{.data.\password}' | base64 -d
fixed

2022-02-15 05:23 UTC, spectro30 commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +kubectl describe certificate -n demo sample-mariadb-server-cert
fixed

2022-02-15 05:27 UTC, spectro30 commented on docs/guides/mariadb/reconfigure-tls/cluster/index.md
> +- `spec.databaseRef.name` specifies that we are performing reconfigure TLS operation on `mg-rs` database.
fixed

2022-02-15 05:29 UTC, spectro30 commented on docs/guides/mariadb/autoscaler/compute/cluster/index.md
> +kubectl get mariadbopsrequest -n demo
fixed

2022-02-15 05:41 UTC, spectro30 commented on docs/guides/mariadb/scaling/vertical-scaling/cluster/index.md
> +$ kubectl get pod -n demo sample-mariadb -o json | jq '.spec.containers[].resources'
fixed

2022-02-15 05:42 UTC, spectro30 commented on docs/guides/mariadb/scaling/horizontal-scaling/cluster/index.md
> +$ kubectl get mariadb -n demo mg-replicaset -o json | jq '.spec.replicas'
fixed

2022-02-15 05:43 UTC, spectro30 commented on docs/guides/mariadb/scaling/horizontal-scaling/cluster/index.md
> +  horizontalScaling
fixed

2022-02-15 05:44 UTC, spectro30 commented on docs/guides/mariadb/scaling/horizontal-scaling/cluster/example/mdops-downscale.yaml
> +  horizontalScaling
fixed

2022-02-15 05:45 UTC, spectro30 commented on docs/guides/mariadb/reconfigure/overview/index.md
> +4. Then, in order to reconfigure the various components (ie. ReplicaSet, Shard, ConfigServer, Mongos, etc.) of the `MariaDB` database the user creates a `MariaDBOpsRequest` CR with desired informatio
fixed

2022-02-15 05:46 UTC, spectro30 commented on docs/guides/mariadb/scaling/vertical-scaling/cluster/index.md
> +$ kubectl get pod -n demo sample-mariadb -o json | jq '.spec.containers[].resources'
fixed

2022-02-15 05:47 UTC, spectro30 commented on docs/guides/mariadb/upgrading/cluster/index.md
> +- `spec.upgrade.targetVersion` specifies the expected version of the database `4.0.5`.
fixed

2022-02-15 05:51 UTC, spectro30 commented on docs/guides/mariadb/volume-expansion/volume-expansion/index.md
> +We can see from the output the `topolvm-provisioner` storage class has `ALLOWVOLUMEEXPANSION` field as true. So, this storage class supports volume expansion. We can use it.
fixed

2022-02-15 06:17 UTC, DRoyyy submitted a review, later dismissed
LGTM

2022-02-15 06:40 UTC, DRoyyy submitted a review, later dismissed

2022-02-18 05:26 UTC, merged