Add Elasticsearch Topology Cluster Docs
kubedb/docs pull request #197
Opened 2022-04-08 08:53 UTC by DRoyyy

Signed-off-by: DRoyyy <diptaroy@appscode.com>

2022-04-08 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/docs?pullRequest=197) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/docs?pullRequest=197) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/docs?pullRequest=197) it.</sub>

2022-04-08 10:01 UTC, kamolhasan requested changes

2022-04-08 10:01 UTC, kamolhasan commented on docs/guides/elasticsearch/clustering/topology-cluster/simple-dedicated-cluster/yamls/es-cluster.yaml
> -  version: searchguard-7.9.3
Use `searchguard-7.14.2`

2022-04-08 10:01 UTC, kamolhasan commented on docs/guides/elasticsearch/clustering/topology-cluster/simple-dedicated-cluster/yamls/es-cluster.yaml
> +      resources:
Remove resources

2022-04-12 09:19 UTC, DRoyyy commented on docs/guides/elasticsearch/clustering/topology-cluster/hot-warm-cold-cluster/index.md
> +Hot-warm-cold architectures are common for time series data such as logging or metrics. For example, assume Elasticsearch is being used to aggregate log files from multiple systems. Logs from today a
solved

2022-04-12 09:19 UTC, DRoyyy commented on docs/guides/elasticsearch/clustering/topology-cluster/hot-warm-cold-cluster/index.md
> +We are going to create a Elasticsearch Hot-Warm-Cold cluster in topology mode. Our cluster will be consist of 2 master nodes, 2 ingest nodes, 1 data content node, 3 data hot nodes, 2 data warm node,
solved

2022-04-12 10:27 UTC, kamolhasan approved these changes
LGTM!

2022-04-12 10:30 UTC, merged