Add Contributor guide
kubedb/docs pull request #232
Opened 2019-07-25 08:33 UTC by weenxin

## Purpose
Recently I have read the KubeDB/operator source code, I write a document to explain how KubeDB operator is implemented. Maybe some other need it.

Maybe there are some errors, Maybe It is totally useless, It is up to you to decide how to deal with this PR.

2019-07-25 09:08 UTC, hossainemruz commented
Thank you @weenxin. We really appreciate it. :+1:

2019-08-07 12:21 UTC, the-redback requested changes
The `images` folder should be moved to either `docs` or `docs/contribution-guide` folder.

2019-08-07 12:21 UTC, the-redback commented on docs/contributor-guide/README.md
> +# KubeDB Operator Design Document
I would prefer some `Installation` and `testing` guide first before jumping into code itself.

2020-02-09 08:53 UTC, tamalsaha commented
I have recorded a video showing we develop and test operators. https://youtu.be/vbOXlWjRjHM 

I am going to document more details as time permits. Feel free to ask me anything.

2020-02-09 08:53 UTC, closed without merging