Update mongo quick-start & concept guide
kubedb/docs pull request #488
Opened 2022-06-13 12:39 UTC by ArnobKumarSaha

Signed-off-by: Arnob kumar saha <arnob@appscode.com>

2022-06-16 04:28 UTC, DRoyyy submitted a review, later dismissed

2022-06-16 04:50 UTC, faem requested changes

2022-06-16 04:50 UTC, faem commented on docs/guides/mongodb/quickstart/quickstart.md
> +persistentvolumeclaim/datadir-mgo-quickstart-2   Bound    pvc-2e6dfb71-056b-4186-927d-855db35d0014   1Gi        RWO            standard       9m30s         standard       9m43s
`         standard       9m43s` extra at the end

2022-06-28 11:50 UTC, faem approved these changes

2022-06-29 05:39 UTC, merged