Add MongoDB Schema Manager
kubedb/docs pull request #500
Opened 2022-09-23 09:18 UTC by DRoyyy

Signed-off-by: DRoyyy <diptaroy@appscode.com>

2022-09-26 06:42 UTC, ArnobKumarSaha requested changes

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/overview/index.md
> +
... the `Schema Manager` operator first verifies if it has the required permission to be able to interact with the referred database-server by checking `Double-OptIn`.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +      readOnly: 0
remove. Mongo schema doesn't have these fields.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +   - readOnly
remove.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +
there also have a field named `maxTTL`, which specifies the maximum time-to-live for the credentials associated with this role.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +  - `scriptPath` accepts a directory location at which the operator should mount the .sql file.
Not `.sql` file,  It will be `.js` file

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +
`volumeSource` can also be emptyDir, nfs, persistantVolumeClaim, hostPath etc

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +    initialized: false
You didn't talk about this `initialized` field anywhere below

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +`spec.deletionPolicy` is a required field that gives flexibility whether to `nullify` (reject) the delete operation or which resources KubeDB should keep or delete when you delete the CRD.
Remove the last part `or which resources KubeDB should keep or delete when you delete the CRD.`.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +`spec.deletionPolicy` is a required field that gives flexibility whether to `nullify` (reject) the delete operation or which resources KubeDB should keep or delete when you delete the CRD.
Also DeletionPolicy is an optional field

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/index.md
> +- Install `KubeVault Enterprise Operator` in your cluster following the steps [here](https://kubevault.com/docs/latest/setup/install/enterprise/).
We also need the stash operator.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/index.md
> +> **Note:** YAML files used in this tutorial are stored in [docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/yamls](https://github.com/kubedb/docs/tree/{{< param "info.version" >}}/docs/guid
the yaml link is not working

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/index.md
> +- `spec.allowedSchemas` specifies the namespace of allowed `Schema Manager`.
Not only namespaces, but also selectors of the schema-manager cr

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +This guide will show you how to to create database and initialize script with MongoDB `Schema Manager` using `KubeDB Enterprise Operator`.
We have a seperate operator for this.  `schema-manager-operator`

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/index.md
> +- Install `KubeVault Enterprise Operator` in your cluster following the steps [here](https://kubevault.com/docs/latest/setup/install/enterprise/).
Add the `stash operator` in other `Before you begin` sections also.  I am not mentioning on all of them.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +- `spec.init` is an optional field, containing the information of a script or a snapshot using which the database should be initialized during creation.
Tell something about `spec.init.script` & its sub-fields, because that is the main focus of this doc.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +- `spec.terminationPolicy` specifies what KubeDB should do when a user try to delete the operation of MySQL CR. *Wipeout* means that the database will be deleted without restrictions. It can also be
`MongoDB` cr, not mysql

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +secret/repo-secret created
There are other two fileds `AWS_ACCESS_KEY_ID` & `AWS_SECRET_ACCESS_KEY` , that you have not talked about.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +### Create ServiceAccount, ClusterRole and ClusterRoleBinding
We can remove the yamls , as we are not showing the backup process here.  Just mentioning the stash references https://stash.run/docs/v2022.07.09/guides/managed-backup/dedicated-backup-namespace/#configure-restore  should be ok.

2022-09-26 06:42 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/overview/index.md
> +
some of the above mentioned changes may have occurred in multiple places.  Please have a check on them if so.

2022-09-27 09:39 UTC, ArnobKumarSaha requested changes

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/deploy-mongodbdatabase/index.md
> +- `spec.terminationPolicy` specifies what KubeDB should do when a user try to delete the operation of MySQL CR. *Wipeout* means that the database will be deleted without restrictions. It can also be
`MongoDB` cr

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +`spec.deletionPolicy` is a optional field that gives flexibility whether to `nullify` (reject) the delete operation.
is an optional field

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/concepts/mongodbdatabase.md
> +
You can only specify either `script` or `snapshot`. Not both together.

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +- `spec.terminationPolicy` specifies what KubeDB should do when a user try to delete the operation of MySQL CR. *Wipeout* means that the database will be deleted without restrictions. It can also be
MongoDB cr

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +- `spec.deletionPolicy` is a required field that gives flexibility whether to `nullify` (reject) the delete operation or which resources KubeDB should keep or delete when you delete the CRD.
optional field.

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +- `spec.deletionPolicy` is a required field that gives flexibility whether to `nullify` (reject) the delete operation or which resources KubeDB should keep or delete when you delete the CRD.
Remove the last part `or which resources KubeDB should keep or delete when you delete the CRD.`

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +This guide will show you how to to create database and initialize snapshot with MongoDB `Schema Manager` using `Schema Manager Operator`.
`how to to` ?!

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +- `spec.allowedSchemas` specifies the namespace of allowed `Schema Manager`.
I already gave changes of this in any of the other md file

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +Here, we are using local backend for storing data snapshots. It can be a cloud storage like GCS bucket, AWS S3, Azure Blob Storage etc. or a Kubernetes persistent volume like HostPath, PersistentVolu
`or a Kubernetes persistent volume like HostPath, PersistentVolumeClaim, NFS etc` .  This sentence doesn't make any sense.  You mean `kubernetes native resources like ...` ?

2022-09-27 09:39 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +- `spec.deletionPolicy` is a required field that gives flexibility whether to `nullify` (reject) the delete operation or which resources KubeDB should keep or delete when you delete the CRD.
same change as others

2022-09-27 12:14 UTC, ArnobKumarSaha requested changes

2022-09-27 12:14 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/overview/index.md
> +4. Once everything is ok in the `MongoDB` server side, then the target database will be created and an entry for that will be entered in the `kubedb_system` database.
4th step from picture says, schema-manager operator creates MongoDB Role.   But here, it is saying something else.  Make the steps consistent. 

Similiar problems in some other steps as well

2022-09-27 12:14 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-script/index.md
> +- `spec.init` is an optional field, containing the information of a script or a snapshot using which the database should be initialized during creation.
Tell something about spec.init.script & its sub-fields, because that is the main focus of this doc.

2022-09-27 12:14 UTC, ArnobKumarSaha commented on docs/guides/mongodb/schema-manager/initializing-with-snapshot/index.md
> +
Give the command for RestoreSession

2022-09-29 10:00 UTC, ArnobKumarSaha approved these changes, later dismissed

2022-10-10 10:46 UTC, ArnobKumarSaha approved these changes

2022-10-10 11:46 UTC, faem approved these changes

2022-10-11 04:04 UTC, merged