Add Percona XtraDB Docs
kubedb/docs pull request #518
Opened 2022-12-19 09:26 UTC by spectro30

Signed-off-by: Md. Alif Biswas <alif@appscode.com>

2022-12-21 11:47 UTC, spectro30 commented
### Before Merge
- Need to update the parent repository
	- Folder name is updated from `percona-xtradb` to `perconaxtradb` (Got rid of the hyphen)
	- Codespan schema check is failing from ProxySQL end

2022-12-23 09:38 UTC, heheh13 commented on docs/guides/percona-xtradb/volume-expansion/volume-expansion/index.md
> +    Mariadb:  2Gi
percona?

2022-12-23 09:38 UTC, heheh13 commented on docs/guides/percona-xtradb/quickstart/overview/examples/sample-mariadb.yaml
> +apiVersion: kubedb.com/v1alpha2
rename the file name?

2022-12-23 09:45 UTC, heheh13 commented on docs/guides/percona-xtradb/private-registry/_index.md
> +title: Run MySQL using Private Registry
percona xtra db?

2022-12-23 09:51 UTC, heheh13 requested changes
- docs/guides/percona-xtradb/autoscaler/compute/overview/images/pxas-compute.png
- docs/guides/percona-xtradb/images/perconaxtradb-lifecycle.png
- https://kubedb-v2-hugo--pr518-add-px-6sjkougz.web.app/docs/v2022.10.18/guides/percona-xtradb/#life-cycle-of-a-perconaxtradb-object

this image contains MariaDB on it 

otherwise looks good to me

2022-12-23 10:02 UTC, spectro30 commented on docs/guides/percona-xtradb/volume-expansion/volume-expansion/index.md
> +    Mariadb:  2Gi
udpated

2022-12-23 10:02 UTC, spectro30 commented on docs/guides/percona-xtradb/quickstart/overview/examples/sample-mariadb.yaml
> +apiVersion: kubedb.com/v1alpha2
fixed

2022-12-23 10:04 UTC, spectro30 commented on docs/guides/percona-xtradb/private-registry/_index.md
> +title: Run MySQL using Private Registry
Updated

2022-12-26 04:57 UTC, heheh13 approved these changes

2022-12-26 05:02 UTC, merged