Update Elasticsearch Documentations
kubedb/docs pull request #519
Opened 2022-12-20 12:37 UTC by raihankhan

Signed-off-by: raihankhan <raihan@appscode.com>

2022-12-29 06:02 UTC, ArnobKumarSaha requested changes

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/README.md
> +
Add Autoscaling feature too

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
externallyManaged should be also be discussed in the below subsection

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
Add missing fields for podTemplate & serviceTemplate too

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
>  ### spec.horizontalScaling
`spec.configuration` is missing

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
>  ### spec.horizontalScaling
+ `spec.restart` & `spec.timeout`

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
>  ### spec.horizontalScaling
Add `AppRef` & `tlsSecret` in AppBinding

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
>  ### spec.horizontalScaling
Add `spec.upgradeConstraints` in ElasticsearchVersion

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
Add `opsRequestOptions` field in Elasticsearch Autoscaler.  
Also, have a check on the fields of `autoscaler.spec.compute`

2022-12-29 06:02 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
Where are the docs of `Upgrade`, `Reconfigure`,`ReconfigureTLS`,  `HorizontalScale`, `VerticalScale`, `Restart` opsRequests ?

2022-12-29 06:05 UTC, raihankhan commented on docs/guides/elasticsearch/README.md
> +
Added

2022-12-29 06:36 UTC, raihankhan commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
Here are the opsReq documentations: [opsReq](https://github.com/kubedb/docs/blob/elasticseach-doc-update/docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md)

2022-12-29 11:47 UTC, raihankhan commented on docs/guides/elasticsearch/concepts/elasticsearch/index.md
> +    externallyManaged: false
Added

2022-12-29 12:01 UTC, raihankhan commented on docs/guides/elasticsearch/concepts/elasticsearch-ops-request/index.md
>  ### spec.horizontalScaling
added

2022-12-30 07:24 UTC, ArnobKumarSaha requested changes
Use the global serach on `docs/guides/elasticsearch` folder,  & search for `mongodb`, `mariadb`, `mysql` etc.    There are many. Change them.

2022-12-30 08:45 UTC, ArnobKumarSaha approved these changes, later dismissed

2023-01-17 10:54 UTC, merged