Add Kafka initial documetations
kubedb/docs pull request #524
Opened 2023-01-04 04:56 UTC by raihankhan

- Add docs for kafka provisioning
- Add docs for kafka crd, version crd
- Add docs for features and demo

Signed-off-by: raihankhan <raihan@appscode.com>

2023-03-30 09:32 UTC, AbdullahAlShaad requested changes

2023-03-30 09:32 UTC, AbdullahAlShaad commented on docs/guides/kafka/clustering/combined-cluster/index.md
> +```bash
$ kubectl get all,secret,pvc -n demo -l 'app.kubernetes.io/instance=kafka-multinode'

2023-03-30 09:32 UTC, AbdullahAlShaad commented on docs/guides/kafka/clustering/topology-cluster/index.md
> +At first, make sure you have cert-manager installed on your k8s for enabling TLS. KubeDB operator uses cert manager to inject certificates into kubernetes secret & uses them for secure `SASL` encrypt
secure SSL encrypted communication

2023-03-30 09:32 UTC, AbdullahAlShaad commented on docs/guides/kafka/concepts/kafka.md
> +`spec.shardTopology` represents the topology configuration for Kafka cluster in KRaft mode.
spec.topology

2023-03-30 09:32 UTC, Shaad7 commented on docs/guides/kafka/concepts/kafka.md
> +Note that, KubeDB does not allow `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` environment variables to set in `spec.podTemplate.spec.env`. If you want to use custom superuser and pas
Remove MongoDB part

2023-03-30 10:31 UTC, raihankhan commented on docs/guides/kafka/clustering/topology-cluster/index.md
> +At first, make sure you have cert-manager installed on your k8s for enabling TLS. KubeDB operator uses cert manager to inject certificates into kubernetes secret & uses them for secure `SASL` encrypt
It's actually `SASL` a mechanism Kafka uses for enabling TLS

2023-03-31 03:36 UTC, Shaad7 submitted a review, later dismissed
LGTM!

2023-03-31 05:04 UTC, raihankhan commented
> LGTM!

.

2023-03-31 05:06 UTC, raihankhan commented
> LGTM!

Thanks. Once the UI is ready we will be able to view the demo preview.

2023-04-01 05:46 UTC, merged