Add pg volume-expansion docs
kubedb/docs pull request #624
Opened 2024-03-18 08:40 UTC by takiaesha

2024-03-18 08:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/docs?pullRequest=624) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/docs?pullRequest=624) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/docs?pullRequest=624) it.</sub>

2024-04-25 11:33 UTC, ArnobKumarSaha requested changes

2024-04-25 11:33 UTC, ArnobKumarSaha commented on docs/guides/elasticsearch/autoscaler/compute/overview/index.md
> +    identifier: es-auto-scaling-Overview
Identifies should be small letter

2024-04-25 11:33 UTC, ArnobKumarSaha commented on docs/guides/mongodb/volume-expansion/replicaset.md
> +    mode: Online
`mode: Online` twice

2024-04-25 11:33 UTC, ArnobKumarSaha commented on docs/guides/mongodb/volume-expansion/standalone.md
> +    mode: Online
same.  Find & remove for this type usages

2024-04-30 04:58 UTC, souravbiswassanto requested changes

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/examples/postgres/volume-expansion/pg-standalone.yaml
> +  replicas: 3
For standalone, replica should be `1`

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/examples/postgres/volume-expansion/pg-ha-cluster.yaml
> +  replicas: 2
make `replicas: 3`

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/examples/postgres/volume-expansion/pg-ha-cluster.yaml
> +apiVersion: kubedb.com/v1alpha2
create a new file named `pg-cluster-with-arbiter.yaml` and provide replicas: 2 there.

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/examples/postgres/volume-expansion/vol-exp-arbiter.yaml
> +    name: pg-ha-cluster
database name should be like this `pg-cluster-with-arbiter`. This name should be provided in ` pg-cluster-with-arbiter.yaml` file.

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/examples/postgres/volume-expansion/vol-exp.yaml
> +apiVersion: ops.kubedb.com/v1alpha1
rename this file as vol-exp-standalone.yaml

2024-04-30 04:58 UTC, souravbiswassanto commented on docs/guides/proxysql/quickstart/mysqlgrp/index.md
> +    identifier: guides-proxysql-quickstart-Overview
make lowercase

2024-04-30 11:58 UTC, souravbiswassanto approved these changes

2024-05-08 06:19 UTC, merged