Add Pgpool Complete Docs
kubedb/docs pull request #650
Opened 2024-07-15 09:20 UTC by MobarakHsn

Signed-off-by: MobarakHsn <mobarak@appscode.com>

2024-08-13 09:04 UTC, raihankhan requested changes

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/reconfigure/overview.md
> +9. After the successful reconfiguring of the `Pgpool`, the `KubeDB` Ops-manager operator resumes the `Pgpool` object so that the `KubeDB` Provisioner  operator resumes its usual operations.
The lines are broken. Re-check them. Happens in all the overviews.

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/scaling/horizontal-scaling/horizontal-ops.md
> +    name: pp-horizontal-scaling-ops
Fix the name here - HorizontalScaling OpsRequest

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/scaling/vertical-scaling/vertical-ops.md
> +    name: pp-vertical-scaling-ops
Fix the name here - VerticalScaling OpsRequest

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/configuration/using-config-file.md
> +    name: Config File
Rename - Customize Configurations

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/configuration/using-init-config.md
> +    name: Init Config
Rename - Customize Init Config

2024-08-13 09:04 UTC, raihankhan commented on docs/guides/pgpool/configuration/using-podtemplate.md
> +
Add some more example - 
1. Refer to this blog for adding custom sidecar containers - [custom container](https://appscode.com/blog/post/add-custom-container-to-kubedb-databases/)

2. Using nodeselector
3. Using taint and tolerations

2024-08-13 09:16 UTC, MobarakHsn commented on docs/guides/pgpool/reconfigure/overview.md
> +9. After the successful reconfiguring of the `Pgpool`, the `KubeDB` Ops-manager operator resumes the `Pgpool` object so that the `KubeDB` Provisioner  operator resumes its usual operations.
These seems some internal issues to all the DB docs. Locally in goland all seems fine!

2024-08-13 09:21 UTC, MobarakHsn commented on docs/guides/pgpool/scaling/horizontal-scaling/horizontal-ops.md
> +    name: pp-horizontal-scaling-ops
Fixed

2024-08-13 09:21 UTC, MobarakHsn commented on docs/guides/pgpool/scaling/vertical-scaling/vertical-ops.md
> +    name: pp-vertical-scaling-ops
Fixed

2024-08-13 09:21 UTC, MobarakHsn commented on docs/guides/pgpool/configuration/using-config-file.md
> +    name: Config File
Fixed

2024-08-13 09:21 UTC, MobarakHsn commented on docs/guides/pgpool/configuration/using-init-config.md
> +    name: Init Config
Fixed

2024-08-14 09:00 UTC, MobarakHsn commented on docs/guides/pgpool/configuration/using-podtemplate.md
> +
Added

2024-08-14 10:01 UTC, raihankhan approved these changes
LGTM 👍🏻

2024-08-14 10:02 UTC, merged