Add `MySQL` backup/restore process by using KubeStash
kubedb/docs pull request #668
Opened 2024-08-30 06:50 UTC by anisurrahman75

Add auto backup

2024-09-02 09:50 UTC, AshrafulHaqueToni commented on docs/guides/mysql/backup/kubestash/auto-backup/index.md
> +If everything goes well, KubeStash should create a `BackupConfiguration` for our MySQL in demo namespace and the phase of that `BackupConfiguration` should be `Ready`. Verify the `BackupConfiguration
If everything is set up correctly, KubeStash will create a `BackupConfiguration` for our MySQL instance in the `demo` namespace. The phase of this `BackupConfiguration` should be `Ready`. You can verify the `BackupConfiguration` object by running the following command,

2024-09-02 10:14 UTC, AshrafulHaqueToni requested changes

2024-09-02 10:14 UTC, AshrafulHaqueToni commented on docs/guides/mysql/backup/kubestash/auto-backup/index.md
> +$ kubectl get backupconfiguration -n demo appbinding-sample-mysql  -o yaml
add the resulted yaml of this command

2024-09-18 06:57 UTC, tapojit047 commented on docs/guides/mysql/backup/kubestash/logical/index.md
> +    --from-file=./RESTIC_PASSWORD \
Remove '\` at the end of command

2024-09-18 11:04 UTC, tapojit047 commented on docs/guides/mysql/backup/kubestash/logical/index.md
> +$ kubectl get snapshots -n demo -l=kubestash.com/repo-name=gcs-demo-repo
kubectl get snapshots -n demo -l=kubestash.com/repo-name=gcs-mysql-repo

2024-09-19 12:44 UTC, tapojit047 commented on docs/guides/mysql/backup/kubestash/customization/index.md
> +    snapshot: latest
we should provide value for snapshot, right?

`snapshot: gcs-mysql-repo-sample-mysql-backup-frequent-backup-1725258600`

2024-09-20 11:01 UTC, tapojit047 commented on docs/guides/mysql/backup/kubestash/application-level/index.md
> +$ kubectl get snapshots -n demo -l=kubestash.com/repo-name=gcs-demo-repo
`gcs-demo-repo` --> `gcs-mysql-repo`

2024-09-25 05:49 UTC, merged