Add Redis backup restore doc for KubeStash
kubedb/docs pull request #675
Opened 2024-09-16 09:44 UTC by Neaj-Morshad-101

2024-09-20 11:36 UTC, AbdullahAlShaad requested changes

2024-09-20 11:36 UTC, AbdullahAlShaad commented on docs/guides/redis/backup/kubestash/application-level/index.md
> +sample-redis   16.1      Ready    9m46s
Wrong Version

2024-09-20 11:36 UTC, AbdullahAlShaad commented on docs/guides/redis/backup/kubestash/application-level/index.md
> +sample-redis   16.1      Ready    9m46s
Create Redis in dev namespace?

2024-09-20 11:38 UTC, Neaj-Morshad-101 commented on docs/guides/redis/backup/kubestash/application-level/index.md
> +sample-redis   16.1      Ready    9m46s
Yes. 
```
  manifestOptions:
    restoreNamespace: dev
```

2024-09-24 04:49 UTC, AbdullahAlShaad requested changes

2024-09-24 04:49 UTC, AbdullahAlShaad commented on docs/guides/redis/initialization/using-script.md
> +- [Backup and Restore](/docs/guides/redis/backup/stash/overview/index.md) Redis databases using Stash.
Give KubeStash link instead of Stash

2024-09-24 05:51 UTC, AbdullahAlShaad approved these changes
LGTM!

2024-09-24 05:51 UTC, merged