Write process of SQL Server PITR
kubedb/docs pull request #700
Opened 2024-10-15 10:34 UTC by anisurrahman75

2024-10-16 13:16 UTC, Neaj-Morshad-101 requested changes

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +kind: MSSQLServerArchiver
Keep this MSSQLServerArchiver yaml manifest in examples

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +$ kubectl apply -f https://github.com/kubedb/docs/raw/{{< param "info.version" >}}/docs/guides/mssqlserver/pitr/examples/sample-mssqlserverarchiver.yaml
link is not valid

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +To install `KubeStash` operator in your cluster following the steps [here](https://github.com/kubestash/installer/tree/master/charts/kubestash).
Now, 
- Install `KubeDB` operator in your cluster following the steps [here](/docs/setup/README.md).
- Install `KubeStash` operator in your cluster following the steps [here]

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +Continuous archiving involves making regular copies (or "archives") of the Microsoft SQL Server transaction log files.To ensure continuous archiving to a remote location we need prepare `BackupStorag
Keep as space between `BackupStorage`, `RetentionPolicy`, `MSSQLServerArchiver`

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +Now, create a `BackupStorage` using this secret. Below is the YAML of `BackupStorage` CR we are going to create,
~~Now, create a BackupStorage using this secret.~~
Now, create a BackupStorage that references this secret.

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/examples/backupstorage.yaml
> +#  deletionPolicy: Delete
remove

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +We are going to store our backed up data into a `GCS` bucket. We have to create a `Secret` with necessary credentials and a `BackupStorage` CR to use this backend. If you want to use a different back
We have to create a `Secret` with necessary credentials `of the cloud bucket`.

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +`MSSQLServerArchiver` is a CR provided by KubeDB for managing the archiving of `MSSQLServer` binlog files and performing volume-level backups.
~~binlog files~~ 
transaction log files.

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +  name: mssqlserverarchiver-sample
mssqlserver-archiver-sample

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +By default, a KubeDB-managed `Microsoft SQL Server` instance run with TLS disabled. However, the `.spec.tls` field is mandatory and will be used during backup and restore operations.
First, an issuer needs to be created, even if TLS is not enabled for SQL Server. The issuer will be used to configure the TLS-enabled Wal-G proxy server, which is required for the SQL Server backup and restore operations.

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +Now, we are going to create an `Issuer` CR using the `mssqlserver-ca` secret that contains the ca-certificate we have just created. Below is the YAML of the `Issuer` cr that we are going to create,
`Issuer` cr -> `Issuer` CR

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +### Deploy Sample Microsoft SQL Server Database
Deploy a sample Microsoft SQL Server Availability Group Cluster

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +      name: mssqlserverarchiver-sample
mssqlserver-archiver-sample

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +        name: mssqlserver-issuer
mssqlserver-issuer -> mssqlserver-ca-issuer

2024-10-16 13:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +      name: mssqlserver-issuer
mssqlserver-issuer -> mssqlserver-ca-issuer

2024-10-16 14:16 UTC, Neaj-Morshad-101 requested changes
We can show the restored manifest once manifest is restored.

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +
> At this point We have a table named `equipment` with 10 rows on the database `demo`

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +restored-mssqlserver-ag-manifest-restorer-7kpn8      0/1     Completed   0          2m31s
restored-mssqlserver-ag-manifest-restorer-7kpn8  -> full backup restorer pod

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +- Pod `restored-mssqlserver-ag-manifest-restorer-7kpn8` is use for full-backup restore.
restored-mssqlserver-ag-manifest-restorer-7kpn8 -> full backup restorer pod

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +2024-10-15 09:57:10.530
remove the query, only mention the timestamp before the drop table command.

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +
I will use a time before drop table

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +      recoveryTimestamp: "2024-10-15T09:57:10.530216Z"
"2024-10-15T09:57:10.530216Z" -> "2024-10-15T09:57:10.530Z"

2024-10-16 14:16 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/examples/restored-mssqlserver-ag.yaml
> +      recoveryTimestamp: "2024-10-15T09:57:10.530216Z"
"2024-10-15T09:57:10.530216Z" -> "2024-10-15T09:57:10.530Z"

2024-10-17 05:04 UTC, anisurrahman75 commented on docs/guides/mssqlserver/pitr/archiver.md
> +  name: mssqlserverarchiver-sample
**mssqlserverarchiver** is a single word as like `mssqlserver`.

2024-10-17 05:18 UTC, Neaj-Morshad-101 commented on docs/guides/mssqlserver/pitr/archiver.md
> +  name: mssqlserverarchiver-sample
It's not readable

2024-10-17 06:51 UTC, ArnobKumarSaha requested changes

2024-10-17 06:51 UTC, ArnobKumarSaha commented on docs/guides/mssqlserver/pitr/examples/sample-mssqlserverarchiver.yaml
> +      container:
Necessary to use `runAsUser: 0` ?

2024-10-17 06:51 UTC, ArnobKumarSaha commented on docs/guides/mssqlserver/pitr/examples/backupstorage.yaml
> +  default: true
Remove `default`

2024-10-17 06:51 UTC, ArnobKumarSaha commented on docs/guides/mssqlserver/pitr/archiver.md
> +        databases: demo
Do we have to specify the taskParams ?  What happens if not specifying anything ?

2024-10-17 06:51 UTC, ArnobKumarSaha commented on docs/guides/mssqlserver/pitr/archiver.md
> +        databases: demo
Do we have to specify the taskParams ?  What happens if not specifying anything ?

2024-10-17 06:51 UTC, ArnobKumarSaha commented on docs/guides/mssqlserver/pitr/archiver.md
> +      namespace: demo
Tell that , We dont have to specify this field.  The archiver will be auto-selected using the `archiver.spec.databases` field.

2024-10-17 07:04 UTC, anisurrahman75 commented on docs/guides/mssqlserver/pitr/examples/sample-mssqlserverarchiver.yaml
> +      container:
Yes, necessary.

2024-10-17 09:42 UTC, ArnobKumarSaha approved these changes

2024-10-17 09:42 UTC, merged