Add MSSQLServer Vertical and Horizontal Scaling Docs
kubedb/docs pull request #703
Opened 2024-10-23 11:13 UTC by Neaj-Morshad-101

2024-10-31 12:44 UTC, takiaesha requested changes

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/horizontal-scaling/overview.md
> +</figure>
image's indication should be proper

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/horizontal-scaling/mssqlserver.md
> +Every 2.0s: kubectl get ms,petset,pods -n demo
remove this line

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/horizontal-scaling/mssqlserver.md
> +Every 2.0s: kubectl get mssqlserveropsrequest -n demo msops-hscale-up
remove

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/horizontal-scaling/mssqlserver.md
> +Every 2.0s: kubectl get mssqlserveropsrequest -n demo msops-hscale-down
remove

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/vertical-scaling/overview.md
> +</figure>
image fix

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/vertical-scaling/overview.md
> +In the next doc, we are going to show a step-by-step guide on updating resources of MSSQLServer database using vertical scaling operation.
add "Next Steps"

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/vertical-scaling/standalone.md
> +Every 2.0s: kubectl get ms,petset,pods -n demo
remove

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/vertical-scaling/standalone.md
> +Every 2.0s: kubectl get mssqlserveropsrequest -n demo mops-vscale-standalone
remove

2024-10-31 12:44 UTC, takiaesha commented on docs/guides/mssqlserver/scaling/vertical-scaling/standalone.md
> +
add next steps if possible

2024-10-31 13:44 UTC, souravbiswassanto requested changes

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +Here, some sample `MSSQLServerOpsRequest` CRs for different administrative operations is given below,
operations are given below

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +
following sub-fields

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +| Type                | Meaning                                                                                   |
this table is not correctly alligned

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +Sample `MSSQLServerOpsRequest` for updating database:
MSSQLServerOpsRequest CR
same changes for other places

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +If you want to scale-up or scale-down your MSSQLServer cluster, you have to specify `spec.horizontalScaling` section. This field consists of the following sub-field:
sub-fields

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +If you want to expand the volume of your MSSQLServer cluster, you have to specify `spec.volumeExpansion` section. This field consists of the following sub-field:
sub-fields

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +| `Updating`          | Specifies such a state that database updating operation has stared                       |
started

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/concepts/opsrequest.md
> +| `Scaling`           | Specifies such a state that the scaling operation on the database has stared              |
started

2024-10-31 13:44 UTC, souravbiswassanto commented on docs/guides/mssqlserver/scaling/horizontal-scaling/mssqlserver.md
> +  Warning  get pvc; ConditionStatus:True                                               54s   KubeDB Ops-manager Operator  get pvc; ConditionStatus:True
remove extra events

2024-11-01 04:59 UTC, souravbiswassanto approved these changes

2024-11-01 07:01 UTC, merged